name: CI

on: [push, pull_request]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Install dependencies
      run: sudo dnf install -y gtkmm4.0-devel libadwaita-devel libcurl-devel gcc cmake git g++ clang openssl-devel
    - name: "[Release g++] Build & Test"
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{github.workspace}}/build
        source-dir: ${{github.workspace}}
        cc: gcc
        cxx: g++
        build-type: Release
        run-test: true
        ctest-options: -V
        configure-options: -DTUMEXAM_CLI_ENABLE_LINTING=OFF -DTUMEXAM_CLI_STATIC_ANALYZE=OFF
  
  clang-tidy:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Install dependencies
      run: sudo dnf install -y gtkmm4.0-devel libadwaita-devel libcurl-devel gcc cmake git g++ clang openssl-devel
    - name: Install clang-tidy
      run: sudo dnf install -y clang-tools-extra
    - name: "[Release g++] Build & Test"
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{github.workspace}}/build
        source-dir: ${{github.workspace}}
        cc: clang
        cxx: clang++
        build-type: Release
        run-test: true
        ctest-options: -V
        configure-options: -DTUMEXAM_CLI_ENABLE_LINTING=ON -DTUMEXAM_CLI_STATIC_ANALYZE=OFF
