name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: Install dependencies
      run: sudo apt install libcurl4-openssl-dev
    - name: "[Release g++] Build & Test"
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{github.workspace}}/build
        source-dir: ${{github.workspace}}
        cc: gcc
        cxx: g++
        build-type: Release
        run-test: true
        ctest-options: -V
        configure-options: -DTUMEXAM_CLI_ENABLE_LINTING=OFF -DTUMEXAM_CLI_STATIC_ANALYZE=OFF
  
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: Install dependencies
      run: sudo apt install libcurl4-openssl-dev
    - name: Install clang-tidy
      run: sudo apt install clang-tidy
    - name: "[Release g++] Build & Test"
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{github.workspace}}/build
        source-dir: ${{github.workspace}}
        cc: clang
        cxx: clang++
        build-type: Release
        run-test: true
        ctest-options: -V
        configure-options: -DTUMEXAM_CLI_ENABLE_LINTING=ON -DTUMEXAM_CLI_STATIC_ANALYZE=OFF
